import { z } from 'zod';

export const ProductSchema = z.object({
  id: z.string(),
  name: z.string(),
  price: z.number(),
  originalPrice: z.number().nullable(),
  discount: z.number().nullable(),
  image: z.string(),
  images: z.array(z.string()),
  colors: z.array(z.string()),
  colorName: z.string(),
  badge: z.string().nullable(),
  href: z.string(),
  category: z.string(),
  material: z.string(),
  size: z.string(),
  blousePiece: z.string().nullable(),
  occasion: z.string(),
  description: z.string(),
  washCare: z.string().nullable(),
  sku: z.string(),
});

export type Product = z.infer<typeof ProductSchema>;

export const products = {
  sarees: [
    {
      id: "soft-silk-green",
      name: "Women Green Soft Silk S",
      price: 3815,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-1.jpg",
      images: ["/images/sarees/saree-1.jpg"],
      colors: ["green", "blue"],
      colorName: "Green with Blue",
      badge: "New",
      href: "/sarees/soft-silk-green",
      category: "Soft Silk",
      material: "Soft Silk",
      size: "6.2m",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Wedding, Occasion",
      description: "This soft silk saree is crafted to offer a perfect balance of elegance and comfort. Made from fine-quality silk, it features a smooth texture with a subtle sheen that enhances its graceful drape. Ideal for festive occasions and special gatherings, this saree reflects timeless tradition while ensuring ease of wear throughout the day.",
      washCare: "Dry clean only to maintain the fabric's sheen and texture. If washing at home, use mild detergent in cold water (gentle hand wash only). Do not bleach or use harsh chemicals. Do not wring or twist the saree.",
      sku: "SS393",
    },
    {
      id: "art-silk-pink",
      name: "Women Pink Art Silk Saree ASS118",
      price: 835,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-2.jpg",
      images: ["/images/sarees/saree-2.jpg"],
      colors: ["pink"],
      colorName: "Pink with Green",
      badge: "Best Seller",
      href: "/sarees/art-silk-pink",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Step into refined elegance with our Art Silk Saree, designed to offer the luxurious sheen of silk with the comfort and ease of lightweight fabric. Soft, smooth, and beautifully drapable, this saree brings out rich colors and intricate patterns that enhance its timeless appeal.",
      washCare: "Do not bleach or use harsh chemicals. Hand wash with mild detergent recommended.",
      sku: "ASS118",
    },
    {
      id: "art-silk-orange",
      name: "Women Orange Art Silk Saree ASS128",
      price: 1175,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-3.jpg",
      images: ["/images/sarees/saree-3.jpg"],
      colors: ["orange"],
      colorName: "Orange",
      badge: null,
      href: "/sarees/art-silk-orange",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Elegant and richly textured, this Art Silk saree beautifully captures the charm of traditional silk with a modern touch. Crafted from premium synthetic fibers, it offers a smooth finish, graceful drape, and a subtle lustre that enhances its visual appeal.",
      washCare: "Hand wash with mild detergent recommended. Do not bleach.",
      sku: "ASS128",
    },
    {
      id: "art-silk-blue",
      name: "Women Blue Art Silk Saree ASS121",
      price: 835,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-4.jpg",
      images: ["/images/sarees/saree-4.jpg"],
      colors: ["blue"],
      colorName: "Blue",
      badge: null,
      href: "/sarees/art-silk-blue",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Step into refined elegance with our Art Silk Saree, designed to offer the luxurious sheen of silk with the comfort and ease of lightweight fabric. Soft, smooth, and beautifully drapable, this saree brings out rich colors and intricate patterns that enhance its timeless appeal.",
      washCare: "Do not bleach or use harsh chemicals. Hand wash with mild detergent recommended.",
      sku: "ASS121",
    },
    {
      id: "art-silk-green",
      name: "Women Green Art Silk Saree ASS116",
      price: 1535,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-5.jpg",
      images: ["/images/sarees/saree-5.jpg"],
      colors: ["green"],
      colorName: "Green",
      badge: "Premium",
      href: "/sarees/art-silk-green",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Step into refined elegance with our Art Silk Saree, designed to offer the luxurious sheen of silk with the comfort and ease of lightweight fabric. Soft, smooth, and beautifully drapable, this saree brings out rich colors and intricate patterns that enhance its timeless appeal.",
      washCare: "Do not bleach or use harsh chemicals. Hand wash with mild detergent recommended.",
      sku: "ASS116",
    },
    {
      id: "art-silk-red",
      name: "Women Red Art Silk Saree ASS114",
      price: 1535,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-6.jpg",
      images: ["/images/sarees/saree-6.jpg"],
      colors: ["red"],
      colorName: "Red",
      badge: null,
      href: "/sarees/art-silk-red",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Step into refined elegance with our Art Silk Saree, designed to offer the luxurious sheen of silk with the comfort and ease of lightweight fabric. Soft, smooth, and beautifully drapable, this saree brings out rich colors and intricate patterns that enhance its timeless appeal.",
      washCare: "Do not bleach or use harsh chemicals. Hand wash with mild detergent recommended.",
      sku: "ASS114",
    },
    {
      id: "art-silk-gold",
      name: "Women Golden Art Silk Saree ASS117",
      price: 1535,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-7.jpg",
      images: ["/images/sarees/saree-7.jpg"],
      colors: ["gold"],
      colorName: "Golden",
      badge: "Premium",
      href: "/sarees/art-silk-gold",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Step into refined elegance with our Art Silk Saree, designed to offer the luxurious sheen of silk with the comfort and ease of lightweight fabric. Soft, smooth, and beautifully drapable, this saree brings out rich colors and intricate patterns that enhance its timeless appeal.",
      washCare: "Do not bleach or use harsh chemicals. Hand wash with mild detergent recommended.",
      sku: "ASS117",
    },
    {
      id: "soft-silk-violet",
      name: "Women Violet Soft Silk Saree SS395",
      price: 3815,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-8.jpg",
      images: ["/images/sarees/saree-8.jpg"],
      colors: ["violet", "blue"],
      colorName: "Violet",
      badge: null,
      href: "/sarees/soft-silk-violet",
      category: "Soft Silk",
      material: "Soft Silk",
      size: "6.2m",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Wedding, Occasion",
      description: "This soft silk saree is crafted to offer a perfect balance of elegance and comfort. Made from fine-quality silk, it features a smooth texture with a subtle sheen that enhances its graceful drape. Ideal for festive occasions and special gatherings, this saree reflects timeless tradition while ensuring ease of wear throughout the day.",
      washCare: "Dry clean only to maintain the fabric's sheen and texture. If washing at home, use mild detergent in cold water (gentle hand wash only). Do not bleach or use harsh chemicals. Do not wring or twist the saree.",
      sku: "SS395",
    },
    {
      id: "soft-silk-mustard",
      name: "Women Mustard Soft Silk Saree SS394",
      price: 3815,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-9.jpg",
      images: ["/images/sarees/saree-9.jpg"],
      colors: ["mustard", "pink"],
      colorName: "Mustard with Pink",
      badge: "New",
      href: "/sarees/soft-silk-mustard",
      category: "Soft Silk",
      material: "Soft Silk",
      size: "6.2m",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Wedding, Occasion",
      description: "This soft silk saree is crafted to offer a perfect balance of elegance and comfort. Made from fine-quality silk, it features a smooth texture with a subtle sheen that enhances its graceful drape. Ideal for festive occasions and special gatherings, this saree reflects timeless tradition while ensuring ease of wear throughout the day.",
      washCare: "Dry clean only to maintain the fabric's sheen and texture. If washing at home, use mild detergent in cold water (gentle hand wash only). Do not bleach or use harsh chemicals. Do not wring or twist the saree.",
      sku: "SS394",
    },
    {
      id: "art-silk-orange-2",
      name: "Women Orange Art Silk Saree ASS120",
      price: 835,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-10.jpg",
      images: ["/images/sarees/saree-10.jpg"],
      colors: ["orange"],
      colorName: "Orange",
      badge: null,
      href: "/sarees/art-silk-orange-2",
      category: "Art Silk",
      material: "Art Silk",
      size: "110cm*620cm",
      blousePiece: "Included (Blouse Running Material)",
      occasion: "Casual, Function",
      description: "Step into refined elegance with our Art Silk Saree, designed to offer the luxurious sheen of silk with the comfort and ease of lightweight fabric. Soft, smooth, and beautifully drapable, this saree brings out rich colors and intricate patterns that enhance its timeless appeal.",
      washCare: "Do not bleach or use harsh chemicals. Hand wash with mild detergent recommended.",
      sku: "ASS120",
    },
  ],
  bedLinen: [
    {
      id: "3d-chadar-beige",
      name: "Bhagalpuri 3D Cotton Chadar - Beige",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-1.jpg",
      images: ["/images/bed-linen/bed-1.jpg"],
      colors: ["beige"],
      colorName: "Beige",
      badge: "Sale",
      href: "/home-linen/3d-chadar-beige",
      category: "3D Cotton Chadar",
      material: "Fine-spun Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri 3D cotton chadars are renowned for their distinctive textured weave and exceptional breathability. This checked pattern variant measures 53 x 100 inches, offering generous coverage for versatile use. The vibrant beige color hue complements traditional and contemporary settings alike. Crafted from pure cotton, this chadar provides comfort in warm climates while maintaining durability through regular wear and washing. The three-dimensional weave creates visual depth and tactile interest, making it a standout piece in any collection.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "3D-CHD-BEI-001",
    },
    {
      id: "3d-chadar-grey",
      name: "Bhagalpuri 3D Cotton Chadar - Grey",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-2.jpg",
      images: ["/images/bed-linen/bed-2.jpg"],
      colors: ["grey"],
      colorName: "Grey",
      badge: "Sale",
      href: "/home-linen/3d-chadar-grey",
      category: "3D Cotton Chadar",
      material: "Fine-spun Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri 3D cotton chadars are renowned for their distinctive textured weave and exceptional breathability. This checked pattern variant measures 53 x 100 inches, offering generous coverage for versatile use. The elegant grey color complements both modern and traditional settings. Crafted from pure cotton, this chadar provides comfort while maintaining durability through regular wear and washing.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "3D-CHD-GRY-001",
    },
    {
      id: "3d-chadar-parrot",
      name: "Bhagalpuri 3D Cotton Chadar - Parrot Green",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-3.jpg",
      images: ["/images/bed-linen/bed-3.jpg"],
      colors: ["green"],
      colorName: "Parrot Green",
      badge: "Sale",
      href: "/home-linen/3d-chadar-parrot",
      category: "3D Cotton Chadar",
      material: "Fine-spun Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri 3D cotton chadars are renowned for their distinctive textured weave and exceptional breathability. This checked pattern variant measures 53 x 100 inches. The vibrant parrot green color adds a splash of traditional charm to any setting. Crafted from pure cotton, this chadar provides comfort in warm climates while maintaining durability.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "3D-CHD-PRT-001",
    },
    {
      id: "3d-chadar-orange",
      name: "Bhagalpuri 3D Cotton Chadar - Pastel Orange",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-4.jpg",
      images: ["/images/bed-linen/bed-4.jpg"],
      colors: ["orange"],
      colorName: "Pastel Orange",
      badge: "Sale",
      href: "/home-linen/3d-chadar-orange",
      category: "3D Cotton Chadar",
      material: "Fine-spun Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri 3D cotton chadars are renowned for their distinctive textured weave and exceptional breathability. This checked pattern variant measures 53 x 100 inches. The pastel orange hue brings warmth and elegance to your bedroom. Perfect for layering, draping, or everyday use.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "3D-CHD-ORN-001",
    },
    {
      id: "dull-andi-parrot",
      name: "Bhagalpuri Dull Andi Chadar - Parrot Green",
      price: 599,
      originalPrice: 1399,
      discount: 57,
      image: "/images/bed-linen/bed-5.jpg",
      images: ["/images/bed-linen/bed-5.jpg"],
      colors: ["green"],
      colorName: "Parrot Green",
      badge: "Sale",
      href: "/home-linen/dull-andi-parrot",
      category: "Dull Andi Chadar",
      material: "Double Thread Cotton",
      size: "54 x 100 inch (137 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri Dull Andi Chadar is crafted from fine-spun cotton providing a silky, soft, and breathable texture. This plain double thread variant in parrot green offers a comfortable feel against the skin. Handcrafted by artisans in Bhagalpur (the 'Silk City of India'), featuring the characteristic slight roughness of authentic Handloom/Khadi.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "DULL-AND-PRT-001",
    },
    {
      id: "designer-chadar",
      name: "Bhagalpuri Designer Cotton Chadar",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-6.jpg",
      images: ["/images/bed-linen/bed-6.jpg"],
      colors: ["multi"],
      colorName: "Lemon Yellow",
      badge: "Sale",
      href: "/home-linen/designer-chadar",
      category: "Designer Cotton Chadar",
      material: "Pure Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri Designer Cotton Chadar features unique patterns crafted by skilled artisans. This premium chadar combines traditional craftsmanship with contemporary design. The lemon yellow hue adds vibrancy to any room. Perfect as a light blanket, bedspread, sofa throw, or meditation mat.",
      washCare: "Machine washable. Wash separately for first few times. Becomes softer with each wash.",
      sku: "DES-COT-LEM-001",
    },
    {
      id: "dull-andi-chadar",
      name: "Bhagalpuri Dull Andi Chadar - Cream",
      price: 599,
      originalPrice: 1399,
      discount: 57,
      image: "/images/bed-linen/bed-7.jpg",
      images: ["/images/bed-linen/bed-7.jpg"],
      colors: ["cream"],
      colorName: "Cream",
      badge: null,
      href: "/home-linen/dull-andi-chadar",
      category: "Dull Andi Chadar",
      material: "Double Thread Cotton",
      size: "54 x 100 inch (137 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri Dull Andi Chadar is crafted from fine-spun cotton providing a silky, soft, and breathable texture. This plain double thread variant in cream offers a comfortable feel against the skin. Handcrafted by artisans in Bhagalpur (the Silk City of India), featuring the characteristic slight roughness of authentic Handloom/Khadi.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "DULL-AND-CRM-001",
    },
    {
      id: "medium-check-chadar",
      name: "Bhagalpuri Medium Check Chadar",
      price: 549,
      originalPrice: 1299,
      discount: 58,
      image: "/images/bed-linen/bed-8.jpg",
      images: ["/images/bed-linen/bed-8.jpg"],
      colors: ["multi"],
      colorName: "Multi Color",
      badge: "Sale",
      href: "/home-linen/medium-check-chadar",
      category: "Medium Check Chadar",
      material: "Cotton",
      size: "52 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri Medium Check Chadar features a classic checkered pattern crafted by skilled artisans. This versatile chadar is perfect for everyday use or special occasions. The multi-color design adds traditional charm to any setting.",
      washCare: "Machine washable. Wash separately for first few times. Becomes softer with each wash.",
      sku: "MED-CHK-MUL-001",
    },
    {
      id: "3d-chadar-beige-2",
      name: "Bhagalpuri 3D Cotton Chadar - Beige (View 2)",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-9.jpg",
      images: ["/images/bed-linen/bed-9.jpg"],
      colors: ["beige"],
      colorName: "Beige",
      badge: "Sale",
      href: "/home-linen/3d-chadar-beige-2",
      category: "3D Cotton Chadar",
      material: "Fine-spun Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri 3D cotton chadars are renowned for their distinctive textured weave and exceptional breathability. This checked pattern variant in beige offers elegant simplicity. Crafted from pure cotton, providing comfort and durability.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "3D-CHD-BEI-002",
    },
    {
      id: "3d-chadar-beige-3",
      name: "Bhagalpuri 3D Cotton Chadar - Beige (View 3)",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-10.jpg",
      images: ["/images/bed-linen/bed-10.jpg"],
      colors: ["beige"],
      colorName: "Beige",
      badge: "Sale",
      href: "/home-linen/3d-chadar-beige-3",
      category: "3D Cotton Chadar",
      material: "Fine-spun Cotton",
      size: "53 x 100 inch (132 x 254 cm)",
      blousePiece: null,
      occasion: "Home, Bedding",
      description: "Bhagalpuri 3D cotton chadars are renowned for their distinctive textured weave and exceptional breathability. This premium variant in beige offers timeless elegance. Crafted from pure cotton, providing comfort and durability for all-season use.",
      washCare: "Machine washable. Becomes softer with each wash. Dry in shade for best results.",
      sku: "3D-CHD-BEI-003",
    },
  ],
};

export const categories = [
  { name: "Sarees", description: "Silk, Cotton, Georgette & more", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDwMCvZKBQGL9oPa_xD3HmfC5WXSt9gnK-WbPuD8ZQiUyhBdJC_j9DY46s55zZRQBjBjok_56A1oTfLIyfkTL5qVxb2hczrhHXyv-Ha_Ri2ybVT4BM6-dvkHb1Mv2QX_Xf0FiAIY3Bow4GMRmqlU5y9GGx2eGiYD6Qqfqspi7wZU6UNMCn2BxsUUV45_Nta4Yp4JNKnSPgE41xYfru0Ra4bFQCs3LMy55se6Ejck2dkUBl17GyaJ4_B8hNh5vzRpI38hohCUXK8TA", href: "/sarees" },
  { name: "Home Linen", description: "Premium Bedspreads & Covers", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFmYHGnO6vEHDPDGkRVQFsaQgmBj8LMo8TVl5EP3Ms748XdbuSv37EgcOvsQ6-nPGU0xV5f1s_eDpW7D3pbhnA-bjKXg-KyicxzSCGOkusLIBdETx6M22f4UESIB740tSE40Y99od8lR97x2S8B_6gwJH5TuryPfyKxJaChSUYZwKAiVJgy3HW70-uV7HSw2J2VECZ-_s2Rads5ow-xOL2IkQK9P5O7jrGdi53mWnr94BFWwWYRbnvx8RRKADtmdRDQKMP9MgCUQ", href: "/home-linen" },
] as const;

export const sareeCategories = [
  { id: "all", label: "All Sarees", count: 10 },
  { id: "soft-silk", label: "Soft Silk", count: 3 },
  { id: "art-silk", label: "Art Silk", count: 7 },
] as const;

export function getProductById(id: string): Product | undefined {
  return products.sarees.find(p => p.id === id) || products.bedLinen.find(p => p.id === id);
}

export function getSareeById(id: string): Product | undefined {
  return products.sarees.find(p => p.id === id);
}

export function getBedLinenById(id: string): Product | undefined {
  return products.bedLinen.find(p => p.id === id);
}

export type SareeProduct = typeof products.sarees[number];
export type BedLinenProduct = typeof products.bedLinen[number];
