export const products = {
  sarees: [
    {
      id: "royal-banarasi-silk",
      name: "Royal Banarasi Silk Saree",
      price: 145,
      originalPrice: 180,
      discount: 20,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBmaJXV4es062MQpiJ_b9JT9C5cW8KjrJtrMGbsJYkQ94ZmM3FtwfMc0O7ZYEt_1GFJDtD2uWsgEffKdyWC8m5uIghv46Uzq4K0N_gsKz1whDDwPgaNRyvtsQRQaeJ4fO_1NGHxCYS7obCO466_oVkb-P4rVRtQWGM3z5zb-GV3VhkIk-SUTU8Lmuav7WFD6elmroQoAs7Hasy-DpGLadlXuFDioE3zrd_4X7Uo7AcjuyQ4af_3sKNkBTbH1D_-xUljNM2M-QjcUg",
      colors: ["#991b1b", "#b45309"],
      badge: "Best Seller",
      href: "/sarees/royal-banarasi-silk",
    },
    {
      id: "kanjivaram-pink",
      name: "Kanjivaram Handloom Pink",
      price: 299,
      originalPrice: null,
      discount: null,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBfPkoQvWaPOngYOn8bbW1TTaCGn7Gj4e9zjvubA4nZwOGqRVi0LGKpzKjcbv96yHAOqopGrSJd05VHccIpsHvaE-czGCSXeQTtvfbnDh_nUh6HmqM3-yS6jpVd5pXg2E9GXlus-iK9J9CLe0JmmLhou0K6a0XslG6OPJzox4KULBPfoyjSEcsj6831lvvy9l5xFz30Qbyff2xj4NPZ8UTo9gOIM7r12R7mSJ5aRkcCeVGJvL6V0xsm7EbZLe5mW1jA2AccNoHFKg",
      colors: ["#ec4899"],
      badge: "New",
      href: "/sarees/kanjivaram-pink",
    },
    {
      id: "midnight-blue-georgette",
      name: "Midnight Blue Georgette",
      price: 89,
      originalPrice: null,
      discount: null,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAiwB0EU0aSuSD6iRlW3ugEy3unH--_1K31OLZ2YdzdyMAT2BepWnDn73Ab9U2tYHppTBIt71VSM20XDsQ13CU6sx0fyuTMUzB5R6Bd2k9RVItd1ss5IrH8Fkgvyt5HHDBSck0uoV6RMcpJzi5FFZHXO1iJyg1sIRoDSX_txvk_lhDF9uzM_L3OtuLIdbpgQRotPo02hHPneS6PjQqgwJckZWMdmxoNjvIZOuBhFc2UhGbjcT6RIH2C344pi_YEqaqyzCce1DFYvg",
      colors: ["#1e3a5f", "#000000"],
      badge: null,
      href: "/sarees/midnight-blue-georgette",
    },
    {
      id: "sunshine-yellow-cotton",
      name: "Sunshine Yellow Cotton",
      price: 45,
      originalPrice: null,
      discount: null,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAQeUpd2fDEX932sYYNj-QQpYx78lfcYAAO19R7Pjob7Lex4K-_jc9t7RGlzJJBQ24qvQyFlgEq8LXFbgojm04o00s7GsIldZwTBGDPXYtJlO769-KaZuF2e8lwfR2TRqzMnGgfhmjabcRyFPJzzSBjbK6LIVEl1tF3p67LKI2AeMxxQuQMkxfLs7_CzZzqc47R3jn_ZiiMb53040ounM_LB51M_wImUlIj0O27CyaaAbXxRHpvNFU4KfeTORLPh_1rI8GWQa5UJA",
      colors: ["#facc15"],
      badge: "Sustainable",
      href: "/sarees/sunshine-yellow-cotton",
    },
    {
      id: "pure-linen-ivory",
      name: "Pure Linen Ivory",
      price: 120,
      originalPrice: null,
      discount: null,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCLoqQzs6jVdLdzR4h4DLIkj5ii1UJ8fKnaiAGSKpmB75EaAj0KgMZ0kQ0kgQuW7wvhL9dYgVPKTo7ZRuZBf0u0gPKzcoMCWgUQ7uFjhBYomiUgNBD2c8rfVMAbxcuPxFgQXWkVq8-QPN9FSN874NjYoAKh0rnUJXv4gK1D7M429qwzPte4pBGmGQll92xOvPb7ZptyaOpNbQqsUXgN7R5PpjKLJsxSya1e-rSybfLdfJA8X_j9KzEOIe4zIPiZXpgVNCbFZRcvIw",
      colors: ["#f5f5f4", "#fde68a"],
      badge: null,
      href: "/sarees/pure-linen-ivory",
    },
    {
      id: "emerald-floral-chiffon",
      name: "Emerald Floral Chiffon",
      price: 65,
      originalPrice: 85,
      discount: 23,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuArzyJL-5cEDc9wIlLjK41OidiH8cP1cXGjaDEFO-sReC67L87pSEfWJyn8b-tuYverVJG8znFMCgVLFvKHdGUBleI6U8KQ3ewb_5EQ4XW_FxY4uuGX3IYkIYKRfxtX_tFcLCexx3ZJfbWQnrQV0mq4axXzw9MLYi_SdCATtG6Ux6nOQpyp-D1DOheCW3C_6nDwRJ8N9HkCxPwEGodFRshLnk8LoBYqEW75xhOwIuanlw40Yw5MhL_d6y3NCYvndEElLfRZs_tNvg",
      colors: ["#059669"],
      badge: "Sold Out Soon",
      href: "/sarees/emerald-floral-chiffon",
    },
  ],
  bedLinen: [
    {
      id: "organic-percale-sheet",
      name: "Organic Percale Sheet Set",
      price: 2499,
      originalPrice: 3200,
      discount: 22,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB6XmbxCY27J3yc7eaAAsmh9vxeab48QsxwHOiVAonK5k6LcvGHIRVRrq8zV8lfu9ydq6G6cd9_hqwz2xBEkJjYUat9i-R3p_010C2sv1rqRIqj-GW2i0-u8Ti4zp6UXadzN_-qeXXDRQ-de3ZZiuT4EAwHjAM77YBdjDDTiyf4CKi36hXwmcnP4XbSOCdElCz50ZxN6lnNggFKoLDHWGw_Ti8gvZpPm3qMLqybqJ1XuDkWPfcYTzwzU0JtvAhYjyYRAGUMj9pLQg",
      colors: ["#d6d3d1"],
      badge: "Eco-friendly",
      href: "/home-linen/organic-percale-sheet",
    },
    {
      id: "sateen-stripe-duvet",
      name: "Sateen Stripe Duvet Cover",
      price: 3199,
      originalPrice: null,
      discount: null,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBeVc2ztZMXz4A3GNLxBjZgFXNAcZQ4-4wjUXWOGSTLvou15Ch9ocVen6R4GK7tSowIhndD1ox2fywzYvfu2hnQK26lQ9k6cUmiBo37A7YXYdEbFR7eDMgxmVEhfo2bZ28NcH2I9QFtFI5AQicRpB_x3MNJja-FpqH57JoYqs1AQMGdkj0YXgPPZdeWjd1WP4CRB5bBb0eL9RYYiDvVM_OEd0OoKda2sIGBmISoRcActu44E_yjlEjSWf2uZcxYTjEv_J3eS7pmPg",
      colors: ["#ffffff"],
      badge: null,
      href: "/home-linen/sateen-stripe-duvet",
    },
    {
      id: "block-print-cotton",
      name: "Block Print Cotton Sheet",
      price: 1899,
      originalPrice: 2500,
      discount: 24,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC2c6v8zdzJBt8_IjEAX9NLpIXgxW1JS3UFGJ9SBHa7QfFMGrcptZeVJa_9xOLA300hWDejBXp4bRxWxud-yrjB9Onakr4bIKDbw7ernJbDUds5GfgOYj113dMHCdT2Zz4y1WGOgazD44fjq9uF8ZL0ir50HHORuBD_Hq-y-Ar7LXz4_AVoRWos3POwx6pF1yGP4mRf92KffKhIiGzvTstfn34frr7wAiIjQuxg3tueWIKmxcluPiktSBBYh2Pbc-X3a3kw42Nf8w",
      colors: ["#1e3a8a", "#ffffff"],
      badge: "Sale",
      href: "/home-linen/block-print-cotton",
    },
    {
      id: "washed-linen-pillowcase",
      name: "Washed Linen Pillowcase Set",
      price: 999,
      originalPrice: null,
      discount: null,
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAvrQlpjyRUIX3rfxG3uYpQJGxWKQd8RutR4hpDcjdGGkZsFnEkc2b2h8wmDA7of4O7sgCboq5Az_T2t3QwUz11W18kZse1cSy34bpRTjr1z6ikNyb03Jh4mr5OAFF147ltmVhs2jTv285RZOy0KwJWYtfG91ddXF30nUnuguj3S1ZhxF3nhCkYySN4eXs_h79MGKO1dLqsi2U29q-APoZhH9sbS21YdDvYQ8fbPV1VDlL6dhHWhFbd_MZhZRZ4tXXePJnRteYmZQ",
      colors: ["#f9a8d4"],
      badge: null,
      href: "/home-linen/washed-linen-pillowcase",
    },
  ],
};

export const categories = [
  {
    name: "Sarees",
    description: "Silk, Cotton, Georgette & more",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDwMCvZKBQGL9oPa_xD3HmfC5WXSt9gnK-WbPuD8ZQiUyhBdJC_j9DY46s55zZRQBjBjok_56A1oTfLIyfkTL5qVxb2hczrhHXyv-Ha_Ri2ybVT4BM6-dvkHb1Mv2QX_Xf0FiAIY3Bow4GMRmqlU5y9GGx2eGiYD6Qqfqspi7wZU6UNMCn2BxsUUV45_Nta4Yp4JNKnSPgE41xYfru0Ra4bFQCs3LMy55se6Ejck2dkUBl17GyaJ4_B8hNh5vzRpI38hohCUXK8TA",
    href: "/sarees",
  },
  {
    name: "Dhotis",
    description: "Traditional Pure Silk & Cotton",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAuom0uV4opeBCD2py_4W_LzHIWHnRdvUHBcQPhC3lJqtYmpQjVVxGsIafZktuBS7XKYbL21QedEIBpJKOfMRMQr6E52xbhmpVO_YYx0iK2lH9el_AQHqmc0eWX9xyDiHq31qJjPaLKO8h1eOozoCMI07l3fgxcskurRENEsM6Zuhjo18J9apIa5tTHq4y4wV_NTDJCorq04xF4kboOCSia_A4rmwbVSUs_U6EVBeIhHq0nBWpvmzDruWn2sUiCu0seIgY4St-9-g",
    href: "/dhotis",
  },
  {
    name: "Home Linen",
    description: "Premium Bedspreads & Covers",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFO6vEHmYHGnDPDGkRVQFsaQgmBj8LMo8TVl5EP3Ms748XdbuSv37EgcOvsQ6-nPGU0xV5f1s_eDpW7D3pbhnA-bjKXg-KyicxzSCGOkusLIBdETx6M22f4UESIB740tSE40Y99od8lR97x2S8B_6gwJH5TuryPfyKxJaChSUYZwKAiVJgy3HW70-uV7HSw2J2VECZ-_s2Rads5ow-xOL2IkQK9P5O7jrGdi53mWnr94BFWwWYRbnvx8RRKADtmdRDQKMP9MgCUQ",
    href: "/home-linen",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    rating: 5,
    date: "2 days ago",
    title: "Absolutely stunning!",
    content: "The saree is exactly as shown in the picture. The blue is vibrant and the gold zari work is very neat. Wore it to my cousin's wedding and got so many compliments. Fast delivery too!",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAdnosVQm6tOTJZroyA2DIhpkp6xfqy9Hc3TwETVWNmM0T0WPZT3hki_24TNeIwOe_-A0f3BZ8Axnw-iYOUJs5XM3dyiLDGgp08I2IuR0tHJuZghgZ8uR746RlEZy7yV83TR3Ovi4-r89BIkAqt-_YEL_E4LN14qqd7fsIlIhAOuzUa_qHmJ8zDFWKdeU47LkHI9jbHkoT1oA21DCMvOsDAWkY-c0VUg7WnD5vNRhiJ9yWnVxExYMW5wkFnx4eeWrrkcm-_EH5WGg",
  },
  {
    id: 2,
    name: "Anjali D.",
    rating: 4,
    date: "1 week ago",
    title: "Good quality but heavy",
    content: "The quality is top-notch, pure silk for sure. However, it's a bit heavier than I expected because of the heavy zari work. Not for daily wear, but perfect for grand functions.",
    avatar: null,
  },
];

export const productSpecs = {
  material: "Pure Katan Silk",
  pattern: "Floral Jangla",
  border: "Gold Zari",
  length: "5.5 Meters",
  blousePiece: "Included (Unstitched)",
  occasion: "Wedding, Party",
  origin: "Varanasi, India",
};
