export const products = {
  sarees: [
    {
      id: "soft-silk-green",
      name: "Women Green Soft Silk Saree SS393",
      price: 3815,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-1.jpg",
      colors: ["green", "blue"],
      badge: "New",
      href: "/sarees/soft-silk-green",
      category: "Soft Silk",
    },
    {
      id: "art-silk-pink",
      name: "Women Pink Art Silk Saree ASS127",
      price: 1175,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-2.jpg",
      colors: ["pink"],
      badge: "Best Seller",
      href: "/sarees/art-silk-pink",
      category: "Art Silk",
    },
    {
      id: "art-silk-orange",
      name: "Women Orange Art Silk Saree ASS128",
      price: 1175,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-3.jpg",
      colors: ["orange"],
      badge: null,
      href: "/sarees/art-silk-orange",
      category: "Art Silk",
    },
    {
      id: "art-silk-blue",
      name: "Women Blue Art Silk Saree ASS121",
      price: 835,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-4.jpg",
      colors: ["blue"],
      badge: null,
      href: "/sarees/art-silk-blue",
      category: "Art Silk",
    },
    {
      id: "art-silk-green",
      name: "Women Green Art Silk Saree ASS116",
      price: 1535,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-5.jpg",
      colors: ["green"],
      badge: "Premium",
      href: "/sarees/art-silk-green",
      category: "Art Silk",
    },
    {
      id: "art-silk-red",
      name: "Women Red Art Silk Saree ASS114",
      price: 1535,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-6.jpg",
      colors: ["red"],
      badge: null,
      href: "/sarees/art-silk-red",
      category: "Art Silk",
    },
    {
      id: "art-silk-gold",
      name: "Women Golden Art Silk Saree ASS117",
      price: 1535,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-7.jpg",
      colors: ["gold"],
      badge: "Premium",
      href: "/sarees/art-silk-gold",
      category: "Art Silk",
    },
    {
      id: "soft-silk-violet",
      name: "Women Violet Soft Silk Saree SS395",
      price: 3815,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-8.jpg",
      colors: ["violet", "blue"],
      badge: null,
      href: "/sarees/soft-silk-violet",
      category: "Soft Silk",
    },
    {
      id: "soft-silk-mustard",
      name: "Women Mustard Soft Silk Saree SS394",
      price: 3815,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-9.jpg",
      colors: ["mustard", "pink"],
      badge: "New",
      href: "/sarees/soft-silk-mustard",
      category: "Soft Silk",
    },
    {
      id: "art-silk-orange-2",
      name: "Women Orange Art Silk Saree ASS120",
      price: 835,
      originalPrice: null,
      discount: null,
      image: "/images/sarees/saree-10.jpg",
      colors: ["orange"],
      badge: null,
      href: "/sarees/art-silk-orange-2",
      category: "Art Silk",
    },
  ],
  bedLinen: [
    {
      id: "3d-chadar-beige",
      name: "Bhagalpuri 3D Cotton Chadar - Beige",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-1.jpg",
      colors: ["beige"],
      badge: "Sale",
      href: "/home-linen/3d-chadar-beige",
    },
    {
      id: "3d-chadar-grey",
      name: "Bhagalpuri 3D Cotton Chadar - Grey",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-2.jpg",
      colors: ["grey"],
      badge: "Sale",
      href: "/home-linen/3d-chadar-grey",
    },
    {
      id: "3d-chadar-parrot",
      name: "Bhagalpuri 3D Cotton Chadar - Parrot Green",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-3.jpg",
      colors: ["green"],
      badge: "Sale",
      href: "/home-linen/3d-chadar-parrot",
    },
    {
      id: "3d-chadar-orange",
      name: "Bhagalpuri 3D Cotton Chadar - Pastel Orange",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-4.jpg",
      colors: ["orange"],
      badge: "Sale",
      href: "/home-linen/3d-chadar-orange",
    },
    {
      id: "dull-andi-parrot",
      name: "Bhagalpuri Dull Andi Chadar - Parrot Green",
      price: 599,
      originalPrice: 1399,
      discount: 57,
      image: "/images/bed-linen/bed-5.jpg",
      colors: ["green"],
      badge: "Sale",
      href: "/home-linen/dull-andi-parrot",
    },
    {
      id: "designer-chadar",
      name: "Bhagalpuri Designer Cotton Chadar",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-6.jpg",
      colors: ["multi"],
      badge: "Sale",
      href: "/home-linen/designer-chadar",
    },
    {
      id: "dull-andi-chadar",
      name: "Bhagalpuri Dull Andi Chadar",
      price: 599,
      originalPrice: 1399,
      discount: 57,
      image: "/images/bed-linen/bed-7.jpg",
      colors: ["cream"],
      badge: null,
      href: "/home-linen/dull-andi-chadar",
    },
    {
      id: "medium-check-chadar",
      name: "Bhagalpuri Medium Check Chadar",
      price: 549,
      originalPrice: 1299,
      discount: 58,
      image: "/images/bed-linen/bed-8.jpg",
      colors: ["multi"],
      badge: "Sale",
      href: "/home-linen/medium-check-chadar",
    },
    {
      id: "3d-chadar-beige-2",
      name: "Bhagalpuri 3D Cotton Chadar - Beige (View 2)",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-9.jpg",
      colors: ["beige"],
      badge: "Sale",
      href: "/home-linen/3d-chadar-beige-2",
    },
    {
      id: "3d-chadar-beige-3",
      name: "Bhagalpuri 3D Cotton Chadar - Beige (View 3)",
      price: 549,
      originalPrice: 1399,
      discount: 60,
      image: "/images/bed-linen/bed-10.jpg",
      colors: ["beige"],
      badge: "Sale",
      href: "/home-linen/3d-chadar-beige-3",
    },
  ],
};

export const categories = [
  {
    name: "Sarees",
    description: "Silk, Cotton, Georgette & more",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDwMCvZKBQGL9oPa_xD3HmfC5WXSt9gnK-WbPuD8ZQiUyhBdJC_j9DY46s55zZRQBjBjok_56A1oTfLIyfkTL5qVxb2hczrhHXyv-Ha_Ri2ybVT4BM6-dvkHb1Mv2QX_Xf0FiAIY3Bow4GMRmqlU5y9GGx2eGiYD6Qqfqspi7wZU6UNMCn2BxsUUV45_Nta4Yp4JNKnSPgE41xYfru0Ra4bFQCs3LMy55se6Ejck2dkUBl17GyaJ4_B8hNh5vzRpI38hohCUXK8TA",
    href: "/sarees",
  },
  {
    name: "Dhotis",
    description: "Traditional Pure Silk & Cotton",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAuom0uV4opeBCD2py_4W_LzHIWHnRdvUHBcQPhC3lJqtYmpQjVVxGsIafZktuBS7XKYbL21QedEIBpJKOfMRMQr6E52xbhmpVO_YYx0iK2lH9el_AQHqmc0eWX9xyDiHq31qJjPaLKO8h1eOozoCMI07l3fgxcskurRENEsM6Zuhjo18J9apIa5tTHq4y4wV_NTDJCorq04xF4kboOCSia_A4rmwbVSUs_U6EVBeIhHq0nBWpvmzDruWn2sUiCu0seIgY4St-9-g",
    href: "/dhotis",
  },
  {
    name: "Home Linen",
    description: "Premium Bedspreads & Covers",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFO6vEHmYHGnDPDGkRVQFsaQgmBj8LMo8TVl5EP3Ms748XdbuSv37EgcOvsQ6-nPGU0xV5f1s_eDpW7D3pbhnA-bjKXg-KyicxzSCGOkusLIBdETx6M22f4UESIB740tSE40Y99od8lR97x2S8B_6gwJH5TuryPfyKxJaChSUYZwKAiVJgy3HW70-uV7HSw2J2VECZ-_s2Rads5ow-xOL2IkQK9P5O7jrGdi53mWnr94BFWwWYRbnvx8RRKADtmdRDQKMP9MgCUQ",
    href: "/home-linen",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    rating: 5,
    date: "2 days ago",
    title: "Absolutely stunning!",
    content: "The saree is exactly as shown in the picture. The quality is excellent and the zari work is very neat. Got so many compliments at my cousin's wedding.",
    avatar: null,
  },
  {
    id: 2,
    name: "Anjali D.",
    rating: 4,
    date: "1 week ago",
    title: "Good quality but heavy",
    content: "The quality is top-notch, pure silk for sure. However, it's a bit heavier than I expected because of the heavy zari work. Perfect for grand functions.",
    avatar: null,
  },
];

export const productSpecs = {
  material: "Pure Katan Silk",
  pattern: "Floral Jangla",
  border: "Gold Zari",
  length: "5.5 Meters",
  blousePiece: "Included (Unstitched)",
  occasion: "Wedding, Party",
  origin: "Varanasi, India",
};

export const sareeCategories = [
  { id: "all", label: "All Sarees", count: 10 },
  { id: "soft-silk", label: "Soft Silk", count: 3 },
  { id: "art-silk", label: "Art Silk", count: 7 },
];
